title: Aleksandar Kuzmanoski Blog
email: aleksandarkuzmanoski11@gmail.com
description: >-
  Hello, I am Aleksandar Kuzmanoski from Gostivar, Macedonia. This is my
  personal blog where you can follow my hobbies, work, and research. Currently,
  I am Data Science Master Student at RWTH Aachen.
baseurl: ''
url: ''
github_username: alkuzman
theme: minima
plugins:
  - jekyll-feed
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      author: Aleksandar Kuzmanoski
